const GET_PRODUCTS = 'GET_PRODUCTS'
const GET_PRODUCTS_BY_NAME = 'GET_PRODUCTS_BY_NAME'
const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
const POST_PRODUCTS = "POST_PRODUCTS"
const BUY_PRODUCT = 'BUY_PRODUCT'

const GET_PLATFORMS = 'GET_PLATFORMS'
const GET_GENDERS = 'GET_GENDERS'
const FILTER_GENDER = 'FILTER_GENDER'
const FILTER_PLATFORM = 'FILTER_PLATFORM'
const ORDER = 'ORDER'

const CHANGE_PAGE = 'CHANGE_PAGE'

const UPDATE_CART = "UPDATE_CART"
const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART"
const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART"
const CLEAR_CART = "CLEAR_CART"


const USER_SESSION = 'USER_SESSION'


// ============== ADMIN ==============

const GET_USERS = 'GET_USERS'



module.exports = {
    GET_PRODUCTS,

    GET_PRODUCTS_BY_NAME,
    GET_PRODUCT_DETAIL,
    BUY_PRODUCT,
    USER_SESSION,
    ORDER,
    GET_PLATFORMS,
    GET_GENDERS,
    FILTER_GENDER,
    FILTER_PLATFORM,
    CHANGE_PAGE,
    POST_PRODUCTS,

    UPDATE_CART,
    REMOVE_ONE_FROM_CART,
    REMOVE_ALL_FROM_CART,
    CLEAR_CART,

    // ADMIN
    GET_USERS
}